#!/bin/bash

# Não executar este script para o próprio usuário freezetemplate
[ "${USER}" = "freezetemplate" ] && exit 0

[ "$(ls -A ${HOME}/.cache)" ] && rm -rf ${HOME}/.cache/*
find ${HOME}/.mozilla -type f -name secmod.db -delete

for i in ${HOME}/.xfce4-session.verbose-log* \
         ${HOME}/.xsession-errors*
do
    [ -f ${i} ] && rm ${i}
done

for i in ${HOME}/.pki/nssdb/pkcs11.txt \
         ${HOME}/.config/gtk-3.0/bookmarks \
         ${HOME}/.config/vlc/vlc-qt-interface.conf \
         ${HOME}/.config/chromium/Default/Preferences \
         ${HOME}/.config/xfce4/desktop/icons.screen*.rc
do
    [ -f ${i} ] && sed -i -e "s@/home/freezetemplate@${HOME}@g" ${i}
done

for i in ${HOME}/.wine/userdef.reg \
         ${HOME}/.wine/user.reg
do
    [ -f ${i} ] && sed -i -e "s@freezetemplate@${USER}@g" ${i}
done
