#!/bin/bash
###########################################################################
# Wraps mount command to create the required directories before
# mounting an OverlayFS union. Intended for use with pam_mount only.
#
# Usage: mount-wrapper <mount args>
#
# Copyright (C) 2016 Prefeitura de Mogi das Cruzes, SP, Brazil
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# On Debian GNU/Linux systems, the complete text of the GNU General
# Public License can be found in `/usr/share/common-licenses/GPL'.
###########################################################################
for arg in "${@}"
do
    case "${arg}" in
    -toverlay)
        mkdir ${!#}/{upper,work}
        chown $(stat -c '%U:%G' ${!#}) ${!#}/{upper,work}
        ;;
    esac
done

exec mount "${@}"
