#!/bin/bash
xorgconf_1=/etc/X11/xorg.conf.d/99-proinfo-urbano.conf
xorgconf_2=/etc/X11/xorg.conf.d/99-proinfo-rural.conf
index=1

while read -r line
do
    address=$(echo "${line}" | cut -d' ' -f1 | tr . :)
    echo TN502_ADDRESS_${index} = ${address}

    for xorgconf in ${xorgconf_1} ${xorgconf_2}
    do
        awk -v n=${index} -v address=${address} \
            '$1 == "BusID" {
                if (++count == n)
                    sub(/[0-9]+:[0-9]+:[0-9]+/, address, $0)
             }
             { print }' ${xorgconf} > ${xorgconf}.tmp && mv ${xorgconf}.tmp ${xorgconf}
    done

    index=$(( index + 1 ))
done < <(lspci | grep SM501)
